name: Release

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Generate test data
        run: bash setup.sh
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

  release:
    name: Release
    needs: test
    permissions:
      contents: write
      packages: write
    uses: semantic-release-action/rust/.github/workflows/release-binary.yml@v5
    secrets:
        cargo-registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        github_app_private_key: ${{ github.token }}
